### ISSUE TITLE
Add test for copying public key

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet-desktop#131]
Scenario: Copy public key
    Given I have unlocked wallet
    And unlocked icon is displayed
    When I click on copy public key
    Then public key is copied

**Comment by jtsang586** [comment]
There's an open issue for Cypress to fix an issue with copy. Until it's fixed it'll be hard to test this properly

https://github.com/cypress-io/cypress/issues/2851

**Comment by dexturr** [comment]
Let's not worry about this for v0.1 then.
