### ISSUE TITLE
Unavailable console message is unhelpful

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vegawallet-desktop#162]
To get here I:
1. Built the app locally (see #160 for build output)
2. Imported the network from vegaprotocol/networks
3. Created a new wallet
4. Opened up the bottom drawer

![image](https://user-images.githubusercontent.com/6678/155316465-11c874b3-efc8-4c9d-a30b-8ae6a378b50f.png)

Asking @ValentinTrinque, `console (Not set)` means that it's not in the config. That wasn't clear to me, and now I know, I'm not sure what I can do next to open up a console and use my wallet.

**Comment by campbellssource** [comment]
Update error message to prompt user to update wallet config.

**Comment by ValentinTrinque** [comment]
I think we could say: `Endpoint not configured` which the clearest we can do for now, IMHO.

**Comment by ValentinTrinque** [comment]
<img width="686" alt="Screenshot 2022-03-16 at 18 13 21" src="https://user-images.githubusercontent.com/4662842/158648531-487e179c-10fc-4aa0-aeef-dcbbd2412b12.png">

@edd Is it better ?
