### ISSUE TITLE
Signed message is hidden

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vegawallet-desktop#163]
See #162 for steps on how I got here, but after clicking on my wallet I went to sign a message (See comment#1 before closing!):

![image](https://user-images.githubusercontent.com/6678/155316889-d51c5456-f43c-4e21-89ee-3ea4b308133b.png)

Everything works correctly up until the point where I hit submit. 
- An empty 'password' field is correctly prevented from submission
- A valid password results in the prompt closing, but nothing else happening
- An invalid password results in the prompt closing, but nothing else happening.

This probably just isn't finished yet, in which case feel free to label as a dupe/wontfix.

**Comment by edd** [comment]
@jeremyletang just pointed out to me that if I scrolled, the response is there:

![image](https://user-images.githubusercontent.com/6678/155317967-6b8ad1fb-042a-43ad-af9b-5ca907a679a1.png)

This isn't clear enough, especially on Linux - I have no scroll bars to indicate the change. Also:

- If I subsequently enter a new message and valid password, the field is updated (but may need more scrolling)
- If I subsequently enter a new message and an invalid password, the message does not change - it's not clear that it didn't change unless I am watching. 

I think both of these would be fixed if the message was cleared when I update the message entry field

![image](https://user-images.githubusercontent.com/6678/155318147-34d327ae-0abd-43f9-8d28-fca80a861581.png)

**Comment by edd** [comment]
Note: this could be feature flagged off if we needed a release soon. It feels very nearly done, just in need of some polish.

**Comment by ValentinTrinque** [comment]
The invalid passphrase problem is present on MacOS as well.

**Comment by ValentinTrinque** [comment]
I will raise a separate PR for the password problem
