### ISSUE TITLE
Wrong passphrase on message signing does not show errors

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#167]
When signing a message with the wrong passphrase, the UI doesn't report the error.

1. An empty 'password' field is correctly prevented from submission
2. An invalid password results in the prompt closing, but nothing else happening

**Comment by edd** [comment]
I mentioned this in https://github.com/vegaprotocol/vegawallet-desktop/issues/163#issue-1148013788 By the way
