### ISSUE TITLE
Support annotating a key

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#205]
This is already implemented on the backend. We need to add it to the UI.

**Comment by candida-d** [comment]
Nice to have but not essential for 0.2 - could be descoped if needed

**Comment by campbellssource** [comment]
Here is a suggested [design](https://www.figma.com/file/W8SV56AAtXpRoQJDQW9ZYt/Vega-Wallet?node-id=1787%3A96525):
<img width="1260" alt="Screenshot 2022-07-11 at 21 17 08" src="https://user-images.githubusercontent.com/13255539/178350648-ac143f03-ca46-4be0-9105-94fc9aa6d87d.png">
