### ISSUE TITLE
Add page to edit application configuration

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#209]
We need to be able to edit the:
- Vega home
- log level
- future telemetry option
- Default network config

For the moment, to minimise the work, we will not hot-reloading the app. So we need to prompt the user a message "Please restart the application to take effect".

**Comment by ValentinTrinque** [comment]
The backend has been merged.

**Comment by candida-d** [comment]
This needs some UX/design decision before it can be implemented (@campbellssource) Should this reintroduce the menu, could it live under a settings icon...?

**Comment by candida-d** [comment]
This should be an option to change later in this section too https://github.com/vegaprotocol/vegawallet-desktop/issues/203

**Comment by campbellssource** [comment]
Here is a mock up of how the ap settings could work with existing implimenatino and the future wireframes.
<img width="2717" alt="Screenshot 2022-06-28 at 17 06 46" src="https://user-images.githubusercontent.com/13255539/176228107-71d091e5-12d3-4427-95f5-c9b271a660dc.png">

**Comment by campbellssource** [comment]
- Suggest App settings happen in a modal,
- Link to it from login screen and the list of keys on a wallet (or the list of wallets if the app hasn't been structured as per longer term design.
- Default network config is not included in this anymore as #84 
- Copy to be edited by @candida-d before merge
- Handle issues with app loading on start with a misconfigured home directory,
- Make it clear that closing the settings screen or canceling we cancel changes
- Sentry radio buttons (note #203 will include a way of setting this on initiation)
- Text to explain what log level is and where log can be found
- For must load with current configuration
- "use default" link is optional, I thought if would be a good way to recover a wallet created on first uses (before the user moved home symlink)
