### ISSUE TITLE
Desktop wallet is not usable on MacOsX Mojave

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/vegawallet-desktop#215]
Here are a couple of issues with running the wallet on an older version of OS-X (Mojave). Look like CSS or rendering issues:

1. Button heights are not calculated correctly, but they are still clickable, user just doesn't know what they do as the text is hidden:

<img width="461" alt="ButtonsFail" src="https://user-images.githubusercontent.com/149245/158849477-7d304095-d93d-433a-b690-4f16a1e4c8b0.png">

2. Clicking on the networks drop down list either crashes something or renders a blank screen - only way out of this is to close and restart the app:

<img width="462" alt="BlankScreen" src="https://user-images.githubusercontent.com/149245/158849653-e81333a9-6344-449b-97e7-57d078f954ec.png">

**Comment by edd** [comment]
I am not seeing this bug with the latest release

**Comment by gordsport** [comment]
Hey @cdm 
This seems to work - please can you re-test now and close if you no longer see the issue?

**Comment by pennyandrews** [comment]
We need to do this https://github.com/vegaprotocol/vegawallet-desktop/issues/365 first

**Comment by ValentinTrinque** [comment]
We need to verify if that's still the case
