### ISSUE TITLE
Associate a network with a wallet

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/vegawallet-desktop#224]
I have a number of wallets but never use the same wallet on more than one network. It would be great if I could set the network for the wallet service separately for each wallet, so that opening one of my test wallets switches the service to Fairground, or opening my mainnet wallet switches it to mainnet, etc.

**Comment by ValentinTrinque** [comment]
We plan to introduce `preferences` later this year

**Comment by campbellssource** [comment]
Related: There has been some mention of encoding a target network into the transaction sent to the wallet for signing.
I think the impact would be that the prompt to sign a message (from the wallet UI) would highlight/warn if the wallet is set to a different network to the one encoded in the transaction.

**Comment by campbellssource** [comment]
My suggested approach would be to have the Desktop wallet behave as you are only logged into one wallet at a time.
For example: for are in the Desktop wallet Signed into a mainnet wallet, You are using a dApp that points at fairground to submit a transaction, The wallet tells you that another wallet has had a request to sign something. You'll be "logged out" of the wallet main net wallet, and into the fairground wallet.
 
I don't think this will be as bad as it sounds as you'll probably need to enter a password between switches.
<img width="1963" alt="Screenshot 2022-06-21 at 11 32 10" src="https://user-images.githubusercontent.com/13255539/174779787-e8b353fb-a8fe-40da-ad43-4b6deb83aa2e.png">
<img width="2799" alt="Screenshot 2022-06-21 at 11 41 31" src="https://user-images.githubusercontent.com/13255539/174781060-827a1bfb-fc52-4a9d-a4c6-00ca5cc2d19d.png">
