### ISSUE TITLE
Handle automatic consent for transactions

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vegawallet-desktop#227]
- Where to prompt the user initiallly
- Where to change this setting later

**Comment by candida-d** [comment]
@ValentinTrinque proposed this would be an advanced feature, in a “danger zone” in the future “config / preferences page”

**Comment by ValentinTrinque** [comment]
That's right. It can be implemented later. And I think, as Candida mentioned, a danger zone is the way to go.

**Comment by candida-d** [comment]
We've had some feedback requesting this option for the desktop wallet app - https://github.com/vegaprotocol/feedback/discussions/114
