### ISSUE TITLE
Handle authentication

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vegawallet-desktop#228]
For key authentication, for now, we think the workflow will be:
1. dApp calls `API.getKey()` -> backend triggers “wallet unlocking and key selection pop-up”
2. dApp get the key -> so it can work with
3. dApp call `API.sendTx()` -> backend triggers “tx review popup”

That’s the responsibility on the user to select the key he wants to use. And the responsibility of the wallet frontend (!= dApp) to help the user to make the right choice “Hey you selected a key without asset attached to it. You sure?”

**Comment by barnabee** [comment]
Per this [message on Slack](https://vegaprotocol.slack.com/archives/C02KSKW6Y3F/p1650384425590019?thread_ts=1650378828.046359&cid=C02KSKW6Y3F) let's have discussion about this before moving to this approach

I can see quite a few pain points this might introduce, especially given that using multiple keys is pretty much essential to risk management across multiple markets, and we have assumed we will eventually have the ability to see balances across many keys, transfer between them, etc. in Console. 

I do see that it would be good not to leak pubkeys or even key descriptions to API clients pre-authorisation but this might also be achievable by allowing customisation of the keyset when a client asks for permission to interact with the wallet. 

So waiting until we understand a bit better what we ought to do would save us making any wrong turns, etc.

**Comment by campbellssource** [comment]
This ticket to track designs for this: https://github.com/vegaprotocol/vegawallet-desktop/issues/229

**Comment by ValentinTrinque** [comment]
This has been done.
