### ISSUE TITLE
Standard menu bar commands missing on Mac OS

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/vegawallet-desktop#232]
The standard commands "Hide Vega Wallet", "Hide Others", "Show all", etc. are missing from the menu bar (see screenshots). This also means standard shortcut keys like cmd-H for hide, etc. do not work.

Not a big issue but it is annoying and worth fixing if easy to bring it in line with other apps on Mac OS.

<img width="230" alt="Screenshot 2022-05-17 at 13 29 41" src="https://user-images.githubusercontent.com/1179257/168801735-946daddb-790c-4d8f-9c6a-1c9c3b4b5004.png">
<img width="264" alt="Screenshot 2022-05-17 at 13 29 31" src="https://user-images.githubusercontent.com/1179257/168801867-c2330773-47f2-4901-9d87-44625cc6f968.png">

**Comment by asiaznik** [comment]
Unfortunately it is not yet supported by `wails`.

I've looked into the wails source code and it looks like there's a plan to suport these native functions so I'd recommend to wait for it in order to fix this issue.

**Comment by asiaznik** [comment]
Although it is possible to handle `cmd+h` from within the app:

```typescript
function isInput(target: EventTarget) {
  return (target as Node).nodeType === Node.ELEMENT_NODE 
    && (
      (target as HTMLElement).tagName.toUpperCase() === "INPUT"
      || (target as HTMLElement).tagName.toUpperCase() === "TEXTAREA"
    );
}

window.addEventListener('keydown', e => {
  if (e.metaKey && e.key === 'h' && !isInput(e.target)) {
    e.preventDefault();
    WindowMinimise();
  }
});
```

**Comment by gordsport** [comment]
@asiaznik As this is not currently supported in wails pushing back for prioritising. Can you try to raise this with them

**Comment by karlem** [comment]
Currently it does not seem to be possible to control other windows (then the app window) with Wails. I have added the option to hide app window but skipped hide,show other windows.

**Comment by ValentinTrinque** [comment]
We can considered it done, then. The other shortcuts require improvements of the native menu bar support on Wails side.
