### ISSUE TITLE
Standard menu bar commands missing on Windows

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#233]
It appears windows version doesn't have menu bar through which we can retrieve the most basic information about the wallet. 

We need to mimic MacOS behavior

**Comment by ckpringle** [comment]
![Image](https://user-images.githubusercontent.com/46783148/193255495-b3be5240-b1aa-4f47-8ecf-ddddd36ecb48.png)

**Comment by ValentinTrinque** [comment]
We need this so, in case we have a problem, user can retrieve the wallet version on all platforms.
