### ISSUE TITLE
SPIKE: network mis-match between dApp and network in wallet (v2 only)

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vegawallet-desktop#235]
As an extension to:

- https://github.com/vegaprotocol/vegawallet-desktop/issues/234

In the above issue the wallet warns the user of a mismatch and they take a manual action. This spike is to investigate:

- [ ] Removing the manual action to switch networks (something like Metamask that is less manual? - informative to the user?)
- [ ] How would network mismatches be handled with walletConnect ?

### For enable trading:
The *very minimum* for this is that the user is presented with a clear useful error message so that they can easily resolve the issue they face.

**Comment by gordsport** [comment]
@gordsport - raise a ticket on wallet:
Needs wallet API endpoint that gives us the vega chain ID so we can also match against the dAPP

**Comment by campbellssource** [comment]
Chain ID gets a new number at the end each restart.
e.g. `vega-mainnet-0006` becomes `vega-mainnet-0007`.
but I guess we could expect the `vega-mainnet` to be the same.
[ref](https://vegaprotocol.slack.com/archives/CFXA4EGN7/p1654874751734249)

**Comment by campbellssource** [comment]
I suggest we schedule this for after the authentication work (where an app needs to be approved by the wallet user)
This is a straw man about how the flow could work.
showing where the there is a network mismatch in the top right.
<img width="1477" alt="Screenshot 2022-07-21 at 20 31 25" src="https://user-images.githubusercontent.com/13255539/180300322-7142b99c-e1a4-46b3-8979-04cebecda43d.png">
 
For desktop wallet (which will soon be reading from a data node) I imagine the UI asks the wallet what network ID it is aligned with (e.g. `vega-mainnet-0007`) and it will show this message if different to what the app is connected to.

but I'm not sure if the CLI wallet has a way of getting a chain ID? @ValentinTrinque 
and have just assumed there will be an API.

I think it is important that it is the dapp that does the work of notifying the user that networks don't match.

**Comment by campbellssource** [comment]
If this ticket is picked up before https://github.com/vegaprotocol/vegawallet-desktop/issues/228 then that step is just skipped and the network check happens one user/password works and you are connected. but before selecting key.

**Comment by pennyandrews** [comment]
Decision in FE backlog blockers call - v1 not going to be available on mainnet and therefore we don't need to do this for v1.

**Comment by ValentinTrinque** [comment]
Retrieving the current chain ID is available on wallet API v2 through `client.get_chain_id` method.

Since we won't support this for API v1, I am closing this issue, since it will work out of the box when the support for wallet service V2 is added.
