### ISSUE TITLE
Wallet crashes after a few trades completed in a row for MacOS v0.2.1 

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/vegawallet-desktop#258]
# Software information
Build info:
- Version: MacOS v0.2.1
- Commit hash: ...

**Tips:** You can get this information from the window located under the `File > About Vegawallet`.

Installation:
- [x] I downloaded it from the GitHub releases page.
- [ ] I built it from my local repository (`wails build`)

# Problem encountered

After placing and approving roughly 6 trades in a row the wallet crashes.

# Observed behaviour
Wallet crashes according the description above.

# Expected behaviour

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:
1) Place long/short
2) Approve trade
3) Trade settles / goes through
4) Place long/short
5) Approve trade
6) Trade settles / goes through
Repeat around 6 trades or so and the wallet crashes, happens on both console V1 and V2

Logs has been included.

## Automation

# Evidence

## Logs

**wallet-app log attached
wallet-service log attached**

## Additional context
Add any other context about the problem here including; system version numbers, components affected.
[2401-2022-07-04-15-29-53.log](https://gi
[2401-2022-07-04-15-29-53.log](https://github.com/vegaprotocol/vegawallet-desktop/files/9040937/2401-2022-07-04-15-29-53.log)
thub.com/vegaprotocol/vegawallet-desktop/files/9040929/2401-2022-07-04-15-29-53.log)

**Comment by wwestgarth** [comment]
I think the issue is that the fairground network has recently changed and had some nodes removed, and your local network information is out of date. We can see this in the error logs where the wallet fails trying to ping these nodes:
```
{"level":"info","@timestamp":"2022-07-04T17:31:34.158+0200","logger":"forwarder","caller":"node/forwarder.go:198","message":"Sending transaction to Vega node","host":"n13.testnet.vega.xyz:3007"}
{"level":"info","@timestamp":"2022-07-04T17:31:34.822+0200","logger":"forwarder","caller":"node/forwarder.go:198","message":"Sending transaction to Vega node","host":"n14.testnet.vega.xyz:3007"}
{"level":"info","@timestamp":"2022-07-04T17:31:35.899+0200","logger":"forwarder","caller":"node/forwarder.go:198","message":"Sending transaction to Vega node","host":"n15.testnet.vega.xyz:3007"}
{"level":"info","@timestamp":"2022-07-04T17:31:37.228+0200","logger":"forwarder","caller":"node/forwarder.go:198","message":"Sending transaction to Vega node","host":"n16.testnet.vega.xyz:3007"}
{"level":"info","@timestamp":"2022-07-04T17:31:40.211+0200","logger":"forwarder","caller":"node/forwarder.go:198","message":"Sending transaction to Vega node","host":"n17.testnet.vega.xyz:3007"}
{"level":"info","@timestamp":"2022-07-04T17:31:42.341+0200","logger":"forwarder","caller":"node/forwarder.go:198","message":"Sending transaction to Vega node","host":"n18.testnet.vega.xyz:3007"}
```

If we look at the fairground nodes in the network file here we can see these ones have been removed: https://github.com/vegaprotocol/networks/blob/master/fairground/fairground.toml#L16

In the desktop-wallet app, if you click the bar at the bottom and go to `Manage networks > Edit`, you will be able to remove the nodes from the list that are no longer running. Then you should hopefully no longer see this issue.
