### ISSUE TITLE
Support administration of networks

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vegawallet-desktop#259]
The flow for updating an existing network's config in desktop wallet is not intuitive ([as referenced in this issue](https://github.com/vegaprotocol/vegawallet-desktop/issues/258#issuecomment-1180255472)). 

Importing a network as new, with the same name, gives you an error of "this network already exists" with an overwrite option, which isn't immediately obvious. It also requires that you know a TOML file URL. Because the networks come pre-loaded, it's not something a user would be expected to know. 

There also doesn't appear to be a way to delete an existing network/config.

**Tasks:**
- [x] Delete a network
- [ ] #526
- [x] Update a network config 
- [ ] #525

**Comment by ckpringle** [comment]
Removing a network is already done, the only thing in there is to be able to update a network's name, and we're good

**Comment by ValentinTrinque** [comment]
We need to investigate what can be done to make the network edition good in terms of UX.

**Comment by ValentinTrinque** [comment]
Closing this issue in favour of dedicated ones
