### ISSUE TITLE
Can't move window while confirmation popup is visible 

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/vegawallet-desktop#263]
# Software information
Build info:
- Version: v0.2.1 (release)
- OS = macOS

Installation:
- [x] I downloaded it from the GitHub releases page.

# Problem encountered
Can't move window by dragging title bar when the txn approval popup is visible (per SS)

<img width="637" alt="Screenshot 2022-07-11 at 11 15 31" src="https://user-images.githubusercontent.com/1179257/178763777-13748201-3bff-4ad6-b33e-28cc7fd2fefc.png">

# Steps to reproduce
Trigger transaction approval popup then try to move the Window

**Comment by asiaznik** [comment]
It happens because we use **inset** title bar and whenever an overlay is displayed it covers the title bar making the interactions on it impossible.
