### ISSUE TITLE
Wallet is crashing/force closing when users attempt to stake tokens

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vegawallet-desktop#274]
### Software information
Build info:
- Version: 0.2.1

### Problem encountered
A couple of people on [Discord Tech Issues](https://discord.com/channels/720571334798737489/915615966556213248/1001412768362143774) are reporting that the wallet is crashing/force closing when they attempt to stake tokens. 

### Information available to users
docs on: [transactions-are-not-being-sent-and-wallet-app-crashes](https://docs.vega.xyz/docs/mainnet/tools/vega-wallet/desktop-app/latest/getting-started#transactions-are-not-being-sent-and-wallet-app-crashes)

**Comment by TomMcL** [comment]
It looks like it's a failing lookup to nodes-guru
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/702798/181019922-bbdcde55-7097-4f2a-9722-0d8bf0cfa826.png">
