### ISSUE TITLE
Fix code coverage report for UI tests

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/vegawallet-desktop#285]
Code coverage report got broken by the Cypress 10 upgrade in #282.

Report seems to be generating locally but in CI it's erroring with the message:
```
Cannot find coverage file /Users/runner/work/vegawallet-desktop/vegawallet-desktop/frontend/automation/.nyc_output/out.json
Skipping coverage report
```

**Comment by radoslaw-szpiech** [comment]
Not applicable anymore. We have working Playwright reports.
