### ISSUE TITLE
Crashers: Desktop Wallet crashes when network issues encountered

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vegawallet-desktop#292]
# Software information
Build info:
- Version: 0.2.1

Operating system:
Reported for Mac (and possibly Windows)  

Installation:
- [x] I downloaded it from the GitHub releases page.
- [ ] I built it from my local repository (`wails build`)

# Problem encountered
Multiple users within and outside of the Vega team have reported that the desktop app crashes in various scenarios. Generally the scenarios seem to be situations when a node is down, or node config is outdated (and thus a node can't be reached), or when the whole nework is down.

When this happens, the wallet app stops responding and needs to be restarted.

**Comment by ckpringle** [comment]
This issue should have disappeared with API v2
