### ISSUE TITLE
Show how to access troubleshooting logs

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vegawallet-desktop#297]
**Resolve with #275 **

Allow users to see where they can get their logs so they can provide the info when troubleshooting a problem. Currently, the only way to find out the log path is by using the CLI wallet, which doesn't help users who are only comfortable with the desktop wallet.

**Comment by pennyandrews** [comment]
Currently the location of the logs is already in the settings, but could improve this to say wallet directory rather than Vega home directory

**Comment by ValentinTrinque** [comment]
@pennyandrews It depends, cause the true name for this directory is the vega home, not just the wallet directory, other vega related files that are not just the wallet can be located there

**Comment by ValentinTrinque** [comment]
This issue is linked to #275.

The solution is to returned the list of all the files and folder a user can be interested in.

That list will be read only and infered based on the vega home. The vega home property will still be empty but the UI can make it look nicer.
