### ISSUE TITLE
Define scope / requirements for web wallet

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-desktop#301]
## Story

As a team
We want to define the MVP scope / requirements for a Vega Web Wallet
So that we can understand and prioritise the work needed

## Acceptance Criteria

- [ ] We have agreed and documented the OS and browsers extension ecosystems we want to support and their priority order
- [ ] We have an understanding of what would need to be different for each
- [ ] We have an understanding of what we could already support with the backend and what would require additional work
- [ ] We have an understand of what we already have UI for and what would require additional work 
- [ ] We have considered in the above what support we want to include for mobile browsers
- [ ] We have considered in the above what we want the Developer Experience to be and therefore the tech approach we take i.e. including things like how we want to publish the UI to decouple it from the Go App, How the app interacts with the libraries and how it it gets wrapped as an extension etc.

**Comment by ValentinTrinque** [comment]
Should issues related to web wallet be moved to a `vegawallet-web` repository ?

**Comment by pennyandrews** [comment]
Recreated the ticket in the correct repo https://github.com/vegaprotocol/browser-wallet/issues/10
