### ISSUE TITLE
Switching network not respected when sending transaction

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vegawallet-desktop#315]
## Description

Switching network does not stop and restart the service

## Steps to Reproduce

1. Open the wallet on mainnet
2. Switch to fairground
3. Place an order, and confirm the tx
4. You will get a 'trading disabled' error message.

## Expected behavior
You should be able to place an order normally on fairground

## Screenshots

![Screen Shot 2022-09-22 at 3 54 52 PM](https://user-images.githubusercontent.com/6803987/191838840-1c80da9c-56f5-423f-8a95-aef4d9b6b2a2.jpg)

## Device details

- Wallet app version, 0.2.1 https://github.com/vegaprotocol/vegawallet-desktop/releases/tag/v0.2.1
- Chrome m1 mac os

## Additional context

If the app starts on the correct network, in this case fairground then the transaction works as expected.

**Comment by ckpringle** [comment]
Should be resolved as part of https://github.com/vegaprotocol/frontend-monorepo/issues/558
