### ISSUE TITLE
Improve how we display incoming transactions (placeholder)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#343]
![Image](https://user-images.githubusercontent.com/46783148/194242212-d40cf50e-265b-4093-825d-33bd9e797d08.png)

**Comment by pennyandrews** [comment]
Might be able to leverage what Elmar is working on for Block Explorer here, maybe publish as a library?

**Comment by ValentinTrinque** [comment]
Superseeded by:
- https://github.com/vegaprotocol/vegawallet-desktop/issues/480

Closing.
