### ISSUE TITLE
Automatically lock / log out of wallet after a period of time

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#351]
## Story 

As a user 
I want to be logged out automatically / have my wallet lock automatically after a period of inactivity 
So that my wallet is kept secure even if I've left it open by mistake

## Acceptance Criteria 

* When a wallet is left in a logged in / viewed stated in the app, and there has been a set period of inactivity (to be defined), I am automatically moved to the wallet listing page and effectively "signed out" of my wallet (i.e. it is now locked)
* To unlock it, I go through the usual steps i.e. select from list, enter passphrase 

## Tasks

Note it may be worth working on this ticket and this one at the same time: 
[Wallet Login: Once per session#360](https://github.com/vegaprotocol/vegawallet-desktop/issues/360)

**Comment by ValentinTrinque** [comment]
It requires work to be done in the backend of the wallet:

https://github.com/vegaprotocol/vega/issues/5736
