### ISSUE TITLE
Add end-to-end tests for wallet API v2

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#355]
Currently the end to end tests don't work whereas it's working when testing manually.

The following tests need to be fixed:

1. `wallet-connection` - handle rejection
2. `transaction-approval` - everything
3. wallet e2e tests ~50% of the time get a timeout error, even many times have to restart it manually to get a green pipeline

**Comment by ckpringle** [comment]
Might want to investigate running the frontend without the backend for the sake of testing.
