### ISSUE TITLE
Wallet Login: Once per session

### ISSUE THREAD

**Issue by AndyWhiteVega** [vegaprotocol/vegawallet-desktop#360]
Log in to a wallet

When using a given wallet, I must select a wallet and enter the passphrase only once per “session” ([0001-WALL-016](https://github.com/vegaprotocol/specs/blob/master/user-interface/0001-WALL-wallet.md#0001-WALL-016))
... so that I am not asked to re-enter frequently

Note it may be worth working on this ticket and this one at the same time:
Automatically lock / log out of wallet after a period of time #351

**Comment by ValentinTrinque** [comment]
It requires work to be done in the backend of the wallet:

- https://github.com/vegaprotocol/vega/issues/5736
