### ISSUE TITLE
Desktop Wallet: Update permissions error

### ISSUE THREAD

**Issue by AndyWhiteVega** [vegaprotocol/vegawallet-desktop#401]
- Ensure multiple keys exist for a given wallet
- Establish a connection via postman
- Select [Manage] alongside connection and grant read access but only for one key
- Now select [none] from the dropdown and you get error shown in 2nd screenshot

![Image](https://user-images.githubusercontent.com/106072061/199259069-098b4914-3ae0-4e22-9a4d-d50862a9b9e8.png)
![Image](https://user-images.githubusercontent.com/106072061/199259125-62d2831b-9339-4f27-94f5-7d9afca7c24c.png)

**Comment by notbot00** [comment]
this has been fixed now as part of https://github.com/vegaprotocol/vegawallet-desktop/commit/ed459fba8793f226701f95d884e2986d631b7506#diff-8b30b03ddf554c808cc8239a05329c04cb3c595cd6c6f92f485f09e90e32e6dfL89-R97
