### ISSUE TITLE
Investigate perfomance issue

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#418]

**Comment by ValentinTrinque** [comment]
We might have identify the origin of the problem in this issue:
- https://github.com/vegaprotocol/vegawallet-desktop/issues/429

Once fixed, we will re-investigate the performance issue to ensure it competely disappeared

**Comment by emilbayes** [comment]
I confirmed that it is fixed on develop after using the updated wallet-ui
