### ISSUE TITLE
Failed to load resource: the server responded with a status of 403/404/503

### ISSUE THREAD

**Issue by ImdioR** [vegaprotocol/vegawallet-desktop#427]
Hello
I would like to report one buy with the latest version that I'm facing now:

I'm trying to send my tokens in stake, the last step, but I'm staked here:
![image](https://user-images.githubusercontent.com/90972248/201783126-c773eb35-cb07-4801-a5c0-238176b7427a.png)

Waiting for confirmation that your change in nomination has been received

----infinite loading...

![image](https://user-images.githubusercontent.com/90972248/201783160-9f95ebca-d99a-4868-857b-66b4b4b2834e.png)

rest-connector.ts:258          POST http://localhost:1789/api/v1/command/sync 503 (Service Unavailable)
![image](https://user-images.githubusercontent.com/90972248/201783194-c9a84b95-f5d1-488c-bf14-8650b60f0372.png)

Looks like localhost Vegawallet can not sync with the website.
Will be grateful for any help or suggestions.

**Comment by ImdioR** [comment]
![image](https://user-images.githubusercontent.com/90972248/201785684-fa544abd-0615-4036-8019-37b17c098c77.png)

![image](https://user-images.githubusercontent.com/90972248/201785606-554dccb7-269e-4a9c-b712-f39e4e9b50ab.png)
![image](https://user-images.githubusercontent.com/90972248/201785706-7f203609-ab55-4412-9c7b-515c2e8a77fb.png)

**Comment by ImdioR** [comment]
![image](https://user-images.githubusercontent.com/90972248/202159251-4e0b64d1-fd9e-4c18-9870-95374ac0d5f0.png)

**Comment by ImdioR** [comment]
I installed the 0.21 version and looks like the connection with Vegawallet was established and everything works well.
Hope that you will fix this bug in the future release.

**Comment by notbot00** [comment]
Glad to hear that. Yes, we indeed fixed this issue in the upcoming release, but the new wallet is not backwards compatible with the software on running on the mainnet network (which is `0.53.0` at the moment), so until the network gets the new software, the 0.2.1 wallet is the one to use. Thank you for your feedback, going to close this issue for now.

**Comment by Jibz26** [comment]
Hello I have the same issue even with the last version 0,21 
Do you have any suggestion to fix it ?
Also, maybe my console is not right :
![image](https://user-images.githubusercontent.com/88749223/210022139-f1381f94-20b7-4675-9eb4-355560aeb9b7.png)
Port number seems failed.

Thank you
