### ISSUE TITLE
Investigate radix-ui component that run out of control

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#429]
It seems a radix-ui component is spinning out of control.

<img width="1335" alt="Screenshot 2022-11-15 at 11 44 30" src="https://user-images.githubusercontent.com/4662842/201900254-9720300b-d633-438a-85f5-34f228cd7728.png">

**Comment by emilbayes** [comment]
Related issue https://github.com/radix-ui/primitives/issues/749

**Comment by emilbayes** [comment]
Seems to be fixed now on the develop branch
