### ISSUE TITLE
[linux] On a fresh install, the app will not launch without installing libwebkit2gtk

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vegawallet-desktop#444]
## Description
On a fresh installation of KDE Neon (under the hood: Ubuntu LTS) `vegwallet` would not launch until I installed `libwebkit2gtk-4.0-dev`.

`sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev`

## Steps to Reproduce

1. Install KDE Neon latest
2. Open Firefox
3. Download vegawallet-desktop v0.5.0
4. Attempt to run it

## Expected behavior

App will not launch. Running it in the command line asks the user to install libwebkitgtk, without specifying a version. To work out the version I needed, I installed golang, then wails, then ran wails doctor. This shouldn't be required

# Device details

Linux xps 5.15.0-56-generic https://github.com/vegaprotocol/vegawallet-desktop/issues/62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
KDE

Operating System: KDE neon 5.26
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.100.0
Qt Version: 5.15.7
Kernel Version: 5.15.0-56-generic (64-bit)
Graphics Platform: X11
Processors: 8 × 11th Gen Intel® Core™ i7-1185G7 @ 3.00GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics
Manufacturer: Dell Inc.
Product Name: XPS 13 9310

**Comment by emilbayes** [comment]
I can confirm this on arch. Since libwebkit2gtk is dynamically linked it must be installed separately. Normally I'd expect a package manager to install this along the app or it to be very clearly detailed in installation instructions.

Here's my sys info:

```
❯ neofetch
                   -`
                  .o+`                   emilbayes@computer
                 `ooo/                   ------------------
                `+oooo:                  OS: Arch Linux x86_64
               `+oooooo:                 Host:
               -+oooooo+:                Kernel: 6.1.10-arch1-1
             `/:-:++oooo+:               Uptime:
            `/++++/+++++++:              Packages: 951 (pacman), 14 (snap)
           `/++++++++++++++:             Shell: bash 5.1.16
          `/+++ooooooooooooo/`           Resolution: 1920x1080
         ./ooosssso++osssssso+`          WM: sway
        .oossssso-````/ossssss+`         Theme:
       -osssssso.      :ssssssso.        Icons:
      :osssssss/        osssso+++.       Terminal:
     /ossssssss/        +ssssooo/-       Terminal Font:
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-10710U (12) @ 4.700GHz
  `+sso+:-`                 `.-/+oso:    GPU: Intel Comet Lake UHD Graphics
 `++:.                           `-/+/   Memory: X MiB / X MiB
```

**Comment by ValentinTrinque** [comment]
That should be resolved out of the box AFAIU:
- 18.12

**Comment by emilbayes** [comment]
Is what you link only for the development part? For releasing I guess either we’d have to publish the vegawallet to various repos so dependencies can be met or statically link dependencies (which would make the binary much larger than it currently is)

**Comment by ValentinTrinque** [comment]
Ok so what I misinterpreted the documentation, the resolution of the required packages is done at compile time. There is not embedded installation in the binary

**Comment by ValentinTrinque** [comment]
We need a better handling of the linux bundles. Will create another issue.
