### ISSUE TITLE
v0.8.x not open in Apple M1 Pro

### ISSUE THREAD

**Issue by azhurbilo** [vegaprotocol/vegawallet-desktop#464]
# Software information
Build info:
- Version: v0.8.x (v0.8.0, v0.8.1, v0.8.2)

Installation:
- [x] I downloaded it from the GitHub releases page.
- [ ] I built it from my local repository (`wails build`)

# Problem encountered

Wallet app doesn't work

# Observed behaviour

Wallet App window closed immediately after starting Vegawallet.app without native mac crash error window

# Expected behaviour

Wallet App window open and works

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:
1. Download testnet build vegawallet-desktop-darwin-arm64.zip, unpack
2. Click Vegawallet.app

ps. Mainnet build is working properly, 0.7.0 testnet build works too

**Comment by notbot00** [comment]
fixed in 0.8.3
