### ISSUE TITLE
Fetching the network file on github sometime fails

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/vegawallet-desktop#472]
## Description

Importing a new network into a desktop wallet on v0.8.3 makes an error appear occasionally.
Red screen of death if you will. Then you try the same thing over and over, restart and try again and it suddenly works.

Several users has reported the issue.

<img width="546" alt="Screenshot 2023-01-31 at 13 26 44" src="https://user-images.githubusercontent.com/100769129/215759669-88d9744f-5a82-4661-97b6-5eb73de2628e.png">

**Comment by gordsport** [comment]
In the first instance we should do the following and see if this is reported again:

- Rephrase the error message to detail whats likely to have happened (GitHub issue?) and request the users to try again.
