### ISSUE TITLE
Migrate MacOS notifications to latest OS framework

### ISSUE THREAD

**Issue by notbot00** [vegaprotocol/vegawallet-desktop#491]
## The Chore

When you install the desktop wallet, OS notifications are disabled by default. We should let the user know that it is possible to turn them on in their OS settings.

**Comment by ValentinTrinque** [comment]
We will have to update our mac os implementation using the user notification kit
https://developer.apple.com/documentation/usernotifications/asking_permission_to_use_notifications?language=objc

**Comment by ValentinTrinque** [comment]
I managed to migrate to the UserNotification framework, but for obscure reasons I couldn't make it work. Something blocks the request for authorization.


In order to give a way out to users, I made sure the application is brought to front when internal requests interactions are raised.
