### ISSUE TITLE
Switch quickly network can corrupt the application configuration

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#498]
When switching network to fast by spamming the button, the “DefaultNetwork” get overwritten so fast that the file is left with previous character, corrupting the file.

We should prevent the user to trigger that update to fast.

<img width="541" alt="Screenshot 2023-02-17 at 14 02 25" src="https://user-images.githubusercontent.com/4662842/219663724-c389f5a5-fb25-447d-b9d3-7719429aaf0e.png">

**Notice the extra `e` at the end, probably from the `false` value of a previous config.**

**Comment by radoslaw-szpiech** [comment]
Also, there is connected issue with that
If you you switch path to config catalog, that does not exist, you get screen as below:
![image](https://user-images.githubusercontent.com/24473278/219687193-2bc86c04-788c-4dc0-bf28-e020e145ba95.png)
At this point:
- User should be informed, that there is no such catalog, or .toml files do not exist.
- There should be some "back" button.
- User is blocked at this point. Even if the app is closed and reopened, only this screen is visible. It should not save config catalog without confirming it's existing and contain correct .toml files.

**Comment by radoslaw-szpiech** [comment]
UPDATE:
It looks like it cannot be reproduced just by switching to not existing catalog, as it just creates new catalog then. It was fixed during writing my comment, or I was just unlucky to experience that. There is still valid issue, if we use Path, that cannot be simply accessed by User - https://github.com/vegaprotocol/vegawallet-desktop/issues/504

**Comment by ValentinTrinque** [comment]
This is done.
