### ISSUE TITLE
REFINE: Create a smart version policy to suggest software updates

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#514]
Questions driving the need:

1. Are we agreed there will always be a desktop wallet release alongside a core release so that there can always be a “matching” wallet version for all core versions?
1. What happens when the difference is massive like if you’re using the current mainnet desktop wallet with Fairground, or with mainnet after the upgrade. This situation will cover most users for a while and needs to be handled extremely well.
1. Do we have any mechanism for future major breaking changes or if we find a security issue and need to signal that upgrading is very important?
1. Is there a difference between how loudly we shout about the mismatch depending on whether the release differ at major, minor, or patch semver level?
1. Do error messages that could be caused by version incompatibility (eg a missing field that is mandatory or something on a txn) do the version check and add an additional message that this could be the reason (or include such a message hard coded)?

**Comment by pennyandrews** [comment]
Merging with #474
