### ISSUE TITLE
Better Linux bundle

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#521]
When trying to launch the app on linux, it fails without the require deps. Three options:

- Statically linked libraries in the application
- Creating installers for each distro
- Improve wails to embed the installation instruction in the binary

Linked issue:
- https://github.com/vegaprotocol/vegawallet-desktop/issues/444

**Comment by emilbayes** [comment]
I volunteer to make the AUR/pacman build. Relevant links:

https://wiki.archlinux.org/title/Arch_package_guidelines
https://wiki.archlinux.org/title/creating_packages
https://wiki.archlinux.org/title/PKGBUILD
https://wiki.archlinux.org/title/Makepkg
