### ISSUE TITLE
Improve the user journey for network management 

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#525]
## Chore 

As a team 
We want to make it clear what options are available to the user to set up a custom network 
So that they can do so in the UI and not encounter the problems we face today - being able to remove a network in the UI but it "coming back"  when you re-open the app, being able to rename a network but it reverting back to the old name etc. 

## Acceptance Criteria 

- [ ] There is a way to view my network list 
- [ ] There is a way to view network details for each network in the list
- [ ] There is a way to add a custom network 
- [ ] I can visually see which networks in my list are preloaded and which are custom 
- [ ] There is a way to add a custom network by duplicating a preloaded network 
- [ ] I can update a preloaded network to the lastest network config if there is one available
- [ ] I can edit a custom network details 
- [ ] There is a way to rename a  custom network 
- [ ] I can delete a custom network 
- [ ] There is a way to be warned I am deleting a network from my list

## Design 

https://www.figma.com/file/eMWtbGPxPHfnVSRsxF8M99/Desktop-Wallet?node-id=2484%3A3930&t=sikT2SgolWAHXhqy-0

## Sketch

![Wallet - Frame 3](https://user-images.githubusercontent.com/46783148/223715501-87c0f21b-75b6-4dce-a0f3-41e492baad83.jpg)

https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764548125640672&cot=14

**Comment by joellecharlotte** [comment]
[Here are the Figma designs](https://www.figma.com/file/eMWtbGPxPHfnVSRsxF8M99/Desktop-Wallet?node-id=2484%3A3930&t=yX5dF6kcVF4AWrjO-1) ↳
