### ISSUE TITLE
There was an error checking for new releases

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#532]
## Description

On first use of the wallet app v0.8.3 I received an error message "There was an error checking for new releases". I wasn't clear why I was receiving the error (I hadn't asked the software to look for an update) and there was no instructions of what I should do to solve it. 

What's causing the error? If it's network connection, perhaps a softer message with a link to refresh / try again like "Unable to check for updates. Try again" would be better?

## Steps to Reproduce

1. Download v 0.8.3 from https://github.com/vegaprotocol/vegawallet-desktop/releases/ on a machine with no existing wallet library (it needs to be a fresh install so that you are forced through the "first use" steps with the pink background) 
2. See error screenshot below

## Screenshots

<img width="1512" alt="Screenshot 2023-02-24 at 16 37 16" src="https://user-images.githubusercontent.com/46783148/221523471-db6c2063-07cb-4363-9ecf-912fc922a447.png">

## Device details

- OS: macOS Catalina v 10.15.7
- Browser: Chrome v 109.0.5414.87

## Additional context

This was the version pointed to from the website, which we've since updated to download v 0.9. I downloaded the Intel version.

**Comment by pennyandrews** [comment]
This is no longer applicable

**Comment by ckpringle** [comment]
Still seeing this 

![Image](https://github.com/vegaprotocol/vegawallet-desktop/assets/46783148/abac1e4e-d8e1-4859-a01e-a2adaa025cb3)
