### ISSUE TITLE
Can't update network config dApp urls

### ISSUE THREAD

**Issue by notbot00** [vegaprotocol/vegawallet-desktop#535]
## Description

Updating network config with dApp urls doesn't happen, even tho we get back a success from the desktop wallet backend.

## Steps to Reproduce

1. open the bottom drawer
2. click manage networks
3. click on one of the Edit buttons for a network
4. put in a url for console, explorer, token
5. scroll down and click update

## Expected behavior

Update the network config. Currently the app displays a success message saying the config got updated, but when you open the config again, the dApp urls are empty. As a result, we can't link transaction hashes to block explorer, because the link to it is always missing.

## Screenshots

<img width="758" alt="Screenshot 2023-02-28 at 15 03 51" src="https://user-images.githubusercontent.com/105208209/221893675-8ac05a45-6ce0-4e8d-a177-12917172d9ed.png">

**Comment by pennyandrews** [comment]
We believe this should have been fixed already but need to verify

**Comment by ValentinTrinque** [comment]
This is a core bug that will be fixed when 0.71.0 will be merged.

**Comment by ValentinTrinque** [comment]
This requires this PR to be merge 
https://github.com/vegaprotocol/vega/pull/8112

It will cause a breaking change on the front end.
