### ISSUE TITLE
Wrong message when network compatibility couldn't be verified

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#539]
## Chore 
Update copy / CTAs in error message when network compatibility couldn't be verified. 

## Tasks 

- [ ] Copy update 

We were unable to verify network compatibility.

Your connection may not work as expected, and transactions may not be seen by the network.

- [ ] Add error message in fixed height panel 
- [ ] Add copy button (so that someone can go troubleshoot themselves)

## Sketch

<img width="1302" alt="Screenshot 2023-03-14 at 09 39 13" src="https://user-images.githubusercontent.com/46783148/224959867-cbf62b08-8573-4d75-8369-fe11bee047c5.png">

## Current message 

<img width="872" alt="Screenshot 2023-03-01 at 20 10 03" src="https://user-images.githubusercontent.com/4662842/222240368-75dc644f-64a1-4b9a-9b0e-db1844be1023.png">

**Comment by joellecharlotte** [comment]
Quick mockup of this, with a max width defined for larger screen sizes. If the wallet is at it's smallest viewport I've stacked the CTAs. [Figma link here](https://www.figma.com/file/eMWtbGPxPHfnVSRsxF8M99/Desktop-Wallet?node-id=2545%3A2901&t=2I4grZMzpe6eEgSB-1) ↳ 

<img width="2504" alt="Network Compatibility" src="https://user-images.githubusercontent.com/113684458/225266392-6e7ac604-ff94-449c-922c-9277fb6a7504.png">
