### ISSUE TITLE
Optimised wallet version per network

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#557]
## User Story

As a user
I want to easily identify the version of the vega wallet I need to use based on the network I will primarily be using it with
So that I can install the app I need quickly and easily and avoid compatibility issues 

### Wallet CI

- [x] Each software has dedicated icons to help differentiate the software.
- [x] Each software have different names "Fairground Wallet" , "Vega Wallet" , "Vega Wallet Dev."
- [x] The github releases process / page is optimised to help users find the latest version of the vegawallet based on the network they want to use it for (as well as understanding what has changed between versions etc.)
- Descoped #680

<img width="1337" alt="Screenshot 2023-03-31 at 10 07 36" src="https://user-images.githubusercontent.com/47143694/229077412-6a68af96-fa86-4f9c-ab7c-e7661ed48fb3.png">

### Wallet UI

- [x] Each software is pre-loaded with only the networks the version is optimised for (vegawallet = mainnet + mainnetmirror) vegawallet (testnet) = testnet, devnet etc.) 
- Descoped #681

### Wallet backend

- [x] We should condition which network prepopulates the computer based on the network the software is optimized for

### Vega.xyz*

- [x] There is a primary CTA to download the mainnet optimised vegawallet version
- [x] There is a secondary CTA to download the testnet optimised vegawallet version
- [x] There is a tertiary CTA to explore all vegawallet releases on github

_*Further improvement of the content of the vega.xyz/wallet page are covered in a [separate ticket in the vega.xyz repo here](https://github.com/vegaprotocol/vega.xyz/issues/501) as they will require content to be written, the page to be redesigned and some work to automatically pick up the latest release links to the wallet software_

## Design 
https://www.figma.com/file/eMWtbGPxPHfnVSRsxF8M99/Desktop-Wallet?node-id=2771-5740&t=oM2F40GatR3w667a-0

## Epic

This story is part of a bigger epic to **[Improve the user experience around software to network compatibility](https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764549808396986&cot=14)**. 

![Wallet - Frame 6](https://user-images.githubusercontent.com/47143694/229140288-2eaefbfa-8420-4f6a-8d31-8f0e41ab2d46.jpg)

This is the full list of tickets that make up the epic:

- #557
- #607
- #610
- #611
- vegaprotocol/vega.xyz#501

**Comment by ckpringle** [comment]
Work in progress https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764549808396986&cot=14 

![Image](https://user-images.githubusercontent.com/46783148/227581443-c6b74628-66e3-4432-b7c0-95795611da9d.jpg)

**Comment by joellecharlotte** [comment]
Attached are the app icons @2x for Mainnet, Fairground and Dev Wallets

<img width="320" alt="App-Icon-Fairground@2x" src="https://user-images.githubusercontent.com/113684458/229068272-284f810b-1add-4643-af1d-ae59b97171b6.png">
 
<img width="320" alt="App-Icon-Mainnet@2x" src="https://user-images.githubusercontent.com/113684458/229068273-ab4e8377-e555-41eb-ab12-0c6ec7430835.png">

<img width="320" alt="App-Icon-Dev@2x" src="https://user-images.githubusercontent.com/113684458/229068267-84d9a6fe-be73-439d-aa79-07465f837813.png">

**Comment by pennyandrews** [comment]
Hey @ValentinTrinque @notbot00 I'm keen to work out if this story is 'done' and perhaps if there are parts of it not done we can work out which should just be separate tickets for the backlog etc. If you could each take a look at the tasks and ticket the ones that you know are done for me that would be super helpful. Thanks!

**Comment by notbot00** [comment]
@pennyandrews as far as I see, this ticket is not done (see the unchecked todo items - i don't have a whole lot of context on what they actually mean). i don't think the backend has been implemented on many of the related tickets either. 
just to confirm, there is no more pending **frontend** work for these tickets, the things which i could, i've implemented, the rest needs the backend to be done.
