### ISSUE TITLE
ERR_FILE_NOT_FOUND when opening wallet

### ISSUE THREAD

**Issue by SuDa2103** [vegaprotocol/vegawallet-desktop#573]
## Description

Some users are seeing this error message - ERR_FILE_NOT_FOUND - when they open the wallet. 

## Steps to Reproduce

1. User has downloaded latest version of wallet (on windows 10 and 11) and tried to open it. 

## Screenshots
![image](https://user-images.githubusercontent.com/55690641/227233171-b4910c71-80c7-4d8a-833d-9f24767f77f7.png)

## Device details

Issue experienced by separate users on both Windows 10 and Windows 11

**Comment by ValentinTrinque** [comment]
related Wails issue:
- https://github.com/wailsapp/wails/issues/940

**Comment by ValentinTrinque** [comment]
We managed to reproduce it when we open the software for mainnet, after we opened the software for fairground. To avoid each software to overright eahcothers cofig, we will introduce separated vega home:
- https://github.com/vegaprotocol/vegawallet-desktop/issues/576
