### ISSUE TITLE
Cannot edit network configuration

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/vegawallet-desktop#588]
## Description

There is error visible each time user tries to submit network changes. It's not possible to save changes.

It breaks existing AC - [0001-WALL-011](https://github.com/vegaprotocol/specs/blob/master/user-interface/0001-WALL-wallet.md#0001-WALL-011)

When fixed, please unskip `network-configuration` tests in `vegawallet-desktop` repo.

## Steps to Reproduce

1. Open app
2. Click networks arrow
3. Click Manage networks
4. Choose any network and click Edit
5. Provide any change (e.g. add dApp address or modify nodes address)
6. Try to submit changes <- Error is visible

## Expected behavior

Changes are saved without any error.

## Screenshots

![Screenshot 2023-03-28 at 12 10 38](https://user-images.githubusercontent.com/24473278/228222773-c9290090-a000-478a-9630-4a31b48ed5a6.png)

**Comment by campbellssource** [comment]
I'm experiencing this too however, my changes are not being saved. the OP says they are saved without error.
I'm using Desktop wallet 0.11 (for Vega.0.70)

**Comment by pennyandrews** [comment]
The fix in .71 needs to be patched into .70 before we can fix the UI

**Comment by notbot00** [comment]
going to close this. tested the network editing, and it seems to work all fine now. also, the tests have been already re-renabled in https://github.com/vegaprotocol/vegawallet-desktop/commit/27af3d68e0edc5b1f380d157c5c0716267a88e80.
