### ISSUE TITLE
Remove password request from removing connection

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-desktop#593]
## The Chore

It feels like overkill to request your password when you remove a connection, the dialogue alone should be enough of a "are you sure" step - however we should have some rules / principles as to when we DO require a password to be entered.

## Tasks
- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

## Sketch

<img width="1327" alt="Screenshot 2023-03-28 at 16 03 54" src="https://user-images.githubusercontent.com/46783148/228281771-c62682a7-26bb-4823-bdda-a4201340a2d6.png">

**Comment by ValentinTrinque** [comment]
This needs:
- https://github.com/vegaprotocol/vega/issues/7223
