### ISSUE TITLE
Fix failing onboarding test after changes to available networks 

### ISSUE THREAD

**Issue by dalebennett1992** [vegaprotocol/vegawallet-desktop#603]
## The Chore
This change https://github.com/vegaprotocol/vegawallet-desktop/pull/577 introduced some new functionality meaning that the 'import default wallets' test started failing. Slack convo here for context

onboarding › import default wallets  ( it’s mistake in the name here, it should be “import default networks”)
Open the app
Open networks available
it should have fairground mainnet1 testnet2
it had only mainnet1
Here I believe it’s intentional change, as basing on PR title :smile: The question is - should we just change the test to expect mainnet1 only, or maybe should we alter the behaviour basing on some env variable?
In the mode the software in compiled in, it should be just mainnet1
## Tasks

- [ ] What do we need to do first
- Update the assertions so it only checks for mainnet
- [ ] and then what?
- (in another PR) amend test cases to update env var, check the corresponding network exists, reset env var at the end of the tests to original value.

**Comment by radoslaw-szpiech** [comment]
Already fixed.
