### ISSUE TITLE
Visually differentiate the wallet based on the network it is optimised for

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-desktop#611]
## User Story

As a user
I want to be able to visually identify which version of the vega wallet i am using AND which network it is optimised for 
So that I can feel confident that I am using the right version for the task I am attempting to achieve 

This is particularly useful for those users that are likely to have multipled version of the vega wallet installed
AND will be beneficial for the project team to aid in the triage of issues that are reported 

### Wallet UI

- [ ] The name and version number of the wallet software is shown in the app header
- [ ] The frontend should be visually differentiated based on the network(s) the software is optimized for Vega Wallet, Fairground Wallet and Vega Wallet Dev. 

<img width="1827" alt="Screenshot 2023-03-29 at 16 54 11" src="https://user-images.githubusercontent.com/46783148/228596545-997c6952-0b6c-4254-bd50-f2b02c39a62c.png">

## Epic

This story is part of a bigger epic to **[Improve the user experience around software to network compatibility](https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764549808396986&cot=14)**. 

![Wallet - Frame 6](https://user-images.githubusercontent.com/47143694/229140288-2eaefbfa-8420-4f6a-8d31-8f0e41ab2d46.jpg)

This is the full list of tickets that make up the epic:

[Optimised wallet version per network](https://github.com/vegaprotocol/vegawallet-desktop/issues/557)
[Handle incompatible networks](https://github.com/vegaprotocol/vegawallet-desktop/issues/607)
[Notify when software update is available](https://github.com/vegaprotocol/vegawallet-desktop/issues/610)
[Visually differentiate the wallet based on the network it is optimised for](https://github.com/vegaprotocol/vegawallet-desktop/issues/611)
[Wallet page improvements](https://github.com/vegaprotocol/vega.xyz/issues/501)

**Comment by ValentinTrinque** [comment]
I merged the backend work. The front end work is missing.
