### ISSUE TITLE
Recovery phrase interactive confirmation

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vegawallet-desktop#65]
Would be good to have some UI that makes users enter their recovery phrase after wallet creation to confirm that they have taken a copy of the phrase.

This could be manual entry of the words or perhaps clicking the words in the right order.

**Comment by campbellssource** [comment]
please add a user interface acceptance criteria here: https://github.com/vegaprotocol/specs/tree/master/user-interface/0001-WALL-wallet.md if/when implemented.

- **must** be prompted to prove that they have an accurate copy of their back up phrase by re-entering the phrase
