### ISSUE TITLE
Wrong window header in v0.11.4

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/vegawallet-desktop#666]
## Description

Window header displays `Vega Wallet 0.11.3` instead of `Vega Wallet 0.11.4`.

## Steps to Reproduce

1. Download & open https://github.com/vegaprotocol/vegawallet-desktop/releases/tag/v0.11.4

## Screenshots

![image](https://user-images.githubusercontent.com/24473278/233647124-aad62157-2d64-4dfa-a024-39119ef36cee.png)

**Comment by mattrussell36** [comment]
Closing as I released wrong, have since deleted it and the tag
