### ISSUE TITLE
Wallet is not letting me edit a network 

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-desktop#686]
## Description

I cannot edit my networks anymore, its unclear why

## Steps to Reproduce

1. Go to vegawallet desktop0.12
2. Click on manage networks
3. I am not able to edit, only remove

## Expected behavior

Should be able to edit ... I could until today

## Screenshots

<img width="763" alt="image" src="https://github.com/vegaprotocol/vegawallet-desktop/assets/89918817/7a1f923b-69d5-410a-9c30-a68b386266be">

## Device details

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 0.12

**Comment by pennyandrews** [comment]
This is how it should be, by design. AND you can work around it by copying the mainnet toml, change the metadata and edit it then
