### ISSUE TITLE
Add health check view to see if nodes are connecting properly

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vegawallet-desktop#71]
If a node is not responding, there's no way to find out without actively researching via CLI and digging around, as per @campbellssource's experience. Having a view that lets someone see if the mainnet node they're connecting to is working well would be a nice thing to have.

**Comment by gordsport** [comment]
Link to notes on possible scope: https://www.notion.so/vegaprotocol/Network-switcher-health-check-ac77dc76f4634ab3a72cb52aaac1c8da

**Comment by pennyandrews** [comment]
For this to be useful we may need to allow someone to change the node you are connected to (in line with the way the other apps work)
